baseURL = "https://unibo-dtm-se.github.io/course-slides"
languageCode = "en-us"
title = "Software Engineering [for Intelligent Distributed Systems] Module 'Principles and Methods'"
disableKinds = ["sitemap", "RSS"]
theme = "reveal-hugo"
publishDir = "build"
ignoreFiles = ['.*generator.md$']

# uncomment for browsing at file:///
# relativeURLs = true
# uglyURLs = true

[author]
name = "Danilo Pianini"

# currently only the unsafe mode for goldmark is supported
[markup.goldmark.renderer]
unsafe = true

# choose between Hugo compile-time or Highlight.js
# syntax highlighting for code inside of code fences
[markup.highlight]
# codeFences = false  # use highlight.js 
codeFences = true  # use hugo highlighting at compile time
style = "tango"  # set a style for hugo highlighting

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
history = true
theme = "league"
highlight_theme = "github"
slide_number = true
transition = "slide"
transition_speed = "fast"
custom_theme = "custom-theme.scss"
custom_theme_compile = true
width = '1920'
height = '1080'
# width = '3840'
# height = '2160'
# width = '100%'
# height = '100%'
[[params.reveal_hugo.mermaid]]
startOnLoad = false
#theme = "default"
# fontFamily = "Inconsolata"
useMaxWidth = false
# actorFontSize = 40
# noteFontSize = 40
# fontSize = 40

[params.reveal_hugo.mermaid.gitGraph]
mainBranchName = 'master'
rotateCommitLabel = true
#fontSize = "3em"
#commitLabelFontSize = '160px'

# [params.reveal_hugo.mermaid.gitGraph.nodeLabel]
# width = 750
# height = 100
# x = -250
# y = 0

#[params.reveal_hugo.mermaid.themeVariables]
#commitLabelColor = '#ff0000'
# commitLabelBackground = '#00ff00'
# commitLabelFontSize = '1.2em'
# tagLabelFontSize = '1.2em'
# labelFontSize = '1.2em'

[params.reveal_hugo.custom_theme_options]
targetPath = "css/custom-theme.css"
enableSourceMap = true
